# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'MainWindow1.ui'
# #
# # Created by: PyQt5 UI code generator 5.9.2
# #
# # WARNING! All changes made in this file will be lost!

# from PyQt5 import QtCore, QtGui, QtWidgets

# class Ui_MainWindow(object):
    
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(1116, 572)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")

#         # btnFile
#         self.btnFile = QtWidgets.QPushButton(self.centralwidget)
#         self.btnFile.setGeometry(QtCore.QRect(20, 10, 101, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(14)
#         font.setBold(True)
#         font.setWeight(75)
#         self.btnFile.setFont(font)
#         self.btnFile.setObjectName("btnFile")

#         # groupBox
#         self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
#         self.groupBox.setGeometry(QtCore.QRect(870, 280, 161, 81))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.groupBox.setFont(font)
#         self.groupBox.setObjectName("groupBox")

#         # btn_blur
#         self.btn_blur = QtWidgets.QPushButton(self.groupBox)
#         self.btn_blur.setGeometry(QtCore.QRect(90, 30, 61, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.btn_blur.setFont(font)
#         self.btn_blur.setObjectName("btn_blur")

#         # rbtn_noise
#         self.rbtn_noise = QtWidgets.QRadioButton(self.groupBox)
#         self.rbtn_noise.setGeometry(QtCore.QRect(20, 30, 61, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         self.rbtn_noise.setFont(font)
#         self.rbtn_noise.setObjectName("rbtn_noise")

#         # groupBox_2
#         self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
#         self.groupBox_2.setGeometry(QtCore.QRect(480, 190, 391, 331))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.groupBox_2.setFont(font)
#         self.groupBox_2.setMouseTracking(False)
#         self.groupBox_2.setAutoFillBackground(True)
#         self.groupBox_2.setObjectName("groupBox_2")

#         # label
#         self.label = QtWidgets.QLabel(self.groupBox_2)
#         self.label.setGeometry(QtCore.QRect(160, 30, 131, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label.setFont(font)
#         self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label.setObjectName("label")

#         # rbtn_ideal
#         self.rbtn_ideal = QtWidgets.QRadioButton(self.groupBox_2)
#         self.rbtn_ideal.setGeometry(QtCore.QRect(20, 30, 101, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setBold(True)
#         font.setWeight(75)
#         self.rbtn_ideal.setFont(font)
#         self.rbtn_ideal.setChecked(False)
#         self.rbtn_ideal.setObjectName("rbtn_ideal")

#         # rbtn_gaussion
#         self.rbtn_gaussion = QtWidgets.QRadioButton(self.groupBox_2)
#         self.rbtn_gaussion.setGeometry(QtCore.QRect(20, 210, 151, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setBold(True)
#         font.setWeight(75)
#         self.rbtn_gaussion.setFont(font)
#         self.rbtn_gaussion.setObjectName("rbtn_gaussion")

#         # rbtn_butter
#         self.rbtn_butter = QtWidgets.QRadioButton(self.groupBox_2)
#         self.rbtn_butter.setGeometry(QtCore.QRect(20, 100, 101, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setBold(True)
#         font.setWeight(75)
#         self.rbtn_butter.setFont(font)
#         self.rbtn_butter.setObjectName("rbtn_butter")

#         # label_5
#         self.label_5 = QtWidgets.QLabel(self.groupBox_2)
#         self.label_5.setGeometry(QtCore.QRect(160, 210, 131, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_5.setFont(font)
#         self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label_5.setObjectName("label_5")

#         # label_6
#         self.label_6 = QtWidgets.QLabel(self.groupBox_2)
#         self.label_6.setGeometry(QtCore.QRect(160, 100, 131, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_6.setFont(font)
#         self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label_6.setObjectName("label_6")


#         # btn_apply_filter
#         self.btn_apply_filter = QtWidgets.QPushButton(self.groupBox_2)
#         self.btn_apply_filter.setGeometry(QtCore.QRect(200, 270, 111, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.btn_apply_filter.setFont(font)
#         self.btn_apply_filter.setObjectName("btn_apply_filter")

#         # label_3
#         self.label_3 = QtWidgets.QLabel(self.groupBox_2)
#         self.label_3.setGeometry(QtCore.QRect(90, 160, 201, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_3.setFont(font)
#         self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label_3.setObjectName("label_3")

#         # txt_order
#         self.txt_order = QtWidgets.QLineEdit(self.groupBox_2)
#         self.txt_order.setGeometry(QtCore.QRect(310, 160, 51, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.txt_order.setFont(font)
#         self.txt_order.setObjectName("txt_order")

#         # txt_cutoff_freq
#         self.txt_cutoff_freq = QtWidgets.QLineEdit(self.groupBox_2)
#         self.txt_cutoff_freq.setGeometry(QtCore.QRect(310, 100, 51, 31))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.txt_cutoff_freq.setFont(font)
#         self.txt_cutoff_freq.setObjectName("txt_cutoff_freq")

#         # label_7
#         self.label_7 = QtWidgets.QLabel(self.groupBox_2)
#         self.label_7.setGeometry(QtCore.QRect(160, 270, 131, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_7.setFont(font)
#         self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label_7.setObjectName("label_7")

#         # centralwidget
#         self.centralwidget.setGeometry(QtCore.QRect(10, 10, 1091, 511))
#         self.centralwidget.setObjectName("centralwidget")

#         MainWindow.setCentralWidget(self.centralwidget)
#         # label_8
#         self.label_8 = QtWidgets.QLabel(self.groupBox_2)
#         self.label_8.setGeometry(QtCore.QRect(100, 280, 191, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_8.setFont(font)
#         self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label_8.setObjectName("label_8")

#         # slider_order
#         self.slider_order = QtWidgets.QSlider(self.groupBox_2)
#         self.slider_order.setGeometry(QtCore.QRect(300, 280, 20, 30))
#         self.slider_order.setOrientation(QtCore.Qt.Horizontal)
#         self.slider_order.setObjectName("slider_order")

#         # label_9
#         self.label_9 = QtWidgets.QLabel(self.groupBox_2)
#         self.label_9.setGeometry(QtCore.QRect(100, 100, 191, 30))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_9.setFont(font)
#         self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
#         self.label_9.setObjectName("label_9")

#         # slider_w
#         self.slider_w = QtWidgets.QSlider(self.groupBox_2)
#         self.slider_w.setGeometry(QtCore.QRect(300, 100, 20, 30))
#         self.slider_w.setOrientation(QtCore.Qt.Horizontal)
#         self.slider_w.setObjectName("slider_w")

#         # btnPreview
#         self.btnPreview = QtWidgets.QPushButton(self.centralwidget)
#         self.btnPreview.setGeometry(QtCore.QRect(510, 110, 101, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.btnPreview.setFont(font)
#         self.btnPreview.setObjectName("btnPreview")

#         # btnPSNR
#         self.btnPSNR = QtWidgets.QPushButton(self.centralwidget)
#         self.btnPSNR.setGeometry(QtCore.QRect(670, 110, 101, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.btnPSNR.setFont(font)
#         self.btnPSNR.setObjectName("btnPSNR")

#         # label_10
#         self.label_10 = QtWidgets.QLabel(self.centralwidget)
#         self.label_10.setGeometry(QtCore.QRect(850, 110, 101, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_10.setFont(font)
#         self.label_10.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_10.setObjectName("label_10")

#         # label_11
#         self.label_11 = QtWidgets.QLabel(self.centralwidget)
#         self.label_11.setGeometry(QtCore.QRect(960, 110, 161, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         self.label_11.setFont(font)
#         self.label_11.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_11.setObjectName("label_11")

#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 31))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#                 # label_12
#         self.label_12 = QtWidgets.QLabel(self.centralwidget)
#         self.label_12.setGeometry(QtCore.QRect(110, 110, 91, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_12.setFont(font)
#         self.label_12.setObjectName("label_12")

#         # label_13
#         self.label_13 = QtWidgets.QLabel(self.centralwidget)
#         self.label_13.setGeometry(QtCore.QRect(210, 110, 91, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_13.setFont(font)
#         self.label_13.setObjectName("label_13")

#         # label_14
#         self.label_14 = QtWidgets.QLabel(self.centralwidget)
#         self.label_14.setGeometry(QtCore.QRect(310, 110, 91, 41))
#         font = QtGui.QFont()
#         font.setFamily("Arial")
#         font.setPointSize(6)
#         font.setBold(True)
#         font.setWeight(75)
#         self.label_14.setFont(font)
#         self.label_14.setObjectName("label_14")

#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 31))
#         self.menubar.setObjectName("menubar")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)

    
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)


#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#         self.btnFile.setText(_translate("MainWindow", "Load"))
#         self.groupBox.setTitle(_translate("MainWindow", "Blur image"))
#         self.btn_blur.setText(_translate("MainWindow", "OK"))
#         self.rbtn_noise.setText(_translate("MainWindow", "Noise"))
#         self.groupBox_2.setTitle(_translate("MainWindow", "Part2"))
#         self.label.setText(_translate("MainWindow", "Cut off frequency"))
#         self.rbtn_ideal.setText(_translate("MainWindow", "Ideal Filter"))
#         self.rbtn_gaussion.setText(_translate("MainWindow", "Gaussion Filter"))
#         self.rbtn_butter.setText(_translate("MainWindow", "Butter Filter"))
#         self.label_5.setText(_translate("MainWindow", "Cut off frequency"))
#         self.label_6.setText(_translate("MainWindow", "Cut off frequency"))
#         self.label_8.setText(_translate("MainWindow", "Order"))
#         self.rbtn_high.setText(_translate("MainWindow", "High pass"))
#         self.rbtn_low.setText(_translate("MainWindow", "Low pass"))
#         self.btn_part2.setText(_translate("MainWindow", "OK"))
#         self.groupBox_3.setTitle(_translate("MainWindow", "Homo Filter"))
#         self.btn_homo.setText(_translate("MainWindow", "OK"))
#         self.label_12.setText(_translate("MainWindow", "Cut off"))
#         self.label_9.setText(_translate("MainWindow", "rH"))
#         self.label_7.setText(_translate("MainWindow", "rL"))
#         self.label_2.setText(_translate("MainWindow", "               Original image"))
#         self.groupBox_6.setTitle(_translate("MainWindow", "Part1"))
#         self.btn_fft.setText(_translate("MainWindow", "FFT"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnFile = QtWidgets.QPushButton(self.centralwidget)
        self.btnFile.setGeometry(QtCore.QRect(650, 10, 101, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnFile.setFont(font)
        self.btnFile.setObjectName("btnFile")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(390, 280, 161, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_blur = QtWidgets.QPushButton(self.groupBox)
        self.btn_blur.setGeometry(QtCore.QRect(90, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.btn_blur.setFont(font)
        self.btn_blur.setObjectName("btn_blur")
        self.rbtn_noise = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_noise.setGeometry(QtCore.QRect(20, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rbtn_noise.setFont(font)
        self.rbtn_noise.setObjectName("rbtn_noise")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 391, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setMouseTracking(False)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(160, 30, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.rbtn_ideal = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtn_ideal.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_ideal.setFont(font)
        self.rbtn_ideal.setChecked(False)
        self.rbtn_ideal.setObjectName("rbtn_ideal")
        self.rbtn_gaussion = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtn_gaussion.setGeometry(QtCore.QRect(20, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_gaussion.setFont(font)
        self.rbtn_gaussion.setObjectName("rbtn_gaussion")
        self.rbtn_butter = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtn_butter.setGeometry(QtCore.QRect(20, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_butter.setFont(font)
        self.rbtn_butter.setObjectName("rbtn_butter")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(160, 210, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(160, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(160, 140, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.butter_cutoff = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.butter_cutoff.setGeometry(QtCore.QRect(310, 100, 62, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.butter_cutoff.setFont(font)
        self.butter_cutoff.setDecimals(1)
        self.butter_cutoff.setMinimum(0.0)
        self.butter_cutoff.setMaximum(999999999.0)
        self.butter_cutoff.setSingleStep(0.5)
        self.butter_cutoff.setProperty("value", 50.0)
        self.butter_cutoff.setObjectName("butter_cutoff")
        self.gaussion_cutoff = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.gaussion_cutoff.setGeometry(QtCore.QRect(310, 210, 62, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.gaussion_cutoff.setFont(font)
        self.gaussion_cutoff.setDecimals(1)
        self.gaussion_cutoff.setMinimum(0.0)
        self.gaussion_cutoff.setMaximum(99999999.0)
        self.gaussion_cutoff.setSingleStep(0.5)
        self.gaussion_cutoff.setProperty("value", 50.0)
        self.gaussion_cutoff.setObjectName("gaussion_cutoff")
        self.ideal_cutoff = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.ideal_cutoff.setGeometry(QtCore.QRect(310, 30, 62, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.ideal_cutoff.setFont(font)
        self.ideal_cutoff.setDecimals(1)
        self.ideal_cutoff.setMinimum(0.0)
        self.ideal_cutoff.setMaximum(9999999.0)
        self.ideal_cutoff.setSingleStep(0.5)
        self.ideal_cutoff.setProperty("value", 50.0)
        self.ideal_cutoff.setObjectName("ideal_cutoff")
        self.butter_order = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.butter_order.setGeometry(QtCore.QRect(310, 140, 62, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.butter_order.setFont(font)
        self.butter_order.setDecimals(1)
        self.butter_order.setMinimum(1.0)
        self.butter_order.setMaximum(50.0)
        self.butter_order.setSingleStep(0.5)
        self.butter_order.setProperty("value", 5.0)
        self.butter_order.setObjectName("butter_order")
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(0, 70, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(0, 180, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(0, 250, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 260, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.rbtn_high = QtWidgets.QRadioButton(self.groupBox_7)
        self.rbtn_high.setGeometry(QtCore.QRect(20, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_high.setFont(font)
        self.rbtn_high.setChecked(True)
        self.rbtn_high.setObjectName("rbtn_high")
        self.rbtn_low = QtWidgets.QRadioButton(self.groupBox_7)
        self.rbtn_low.setGeometry(QtCore.QRect(180, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.rbtn_low.setFont(font)
        self.rbtn_low.setObjectName("rbtn_low")
        self.btn_part2 = QtWidgets.QPushButton(self.groupBox_7)
        self.btn_part2.setGeometry(QtCore.QRect(310, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.btn_part2.setFont(font)
        self.btn_part2.setObjectName("btn_part2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 360, 241, 161))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_homo = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_homo.setGeometry(QtCore.QRect(160, 110, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.btn_homo.setFont(font)
        self.btn_homo.setObjectName("btn_homo")
        self.spin_rh = QtWidgets.QSpinBox(self.groupBox_3)
        self.spin_rh.setGeometry(QtCore.QRect(90, 30, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.spin_rh.setFont(font)
        self.spin_rh.setMinimum(1)
        self.spin_rh.setMaximum(100)
        self.spin_rh.setSingleStep(1)
        self.spin_rh.setObjectName("spin_rh")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(30, 110, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.spin_rl = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_rl.setGeometry(QtCore.QRect(90, 70, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.spin_rl.setFont(font)
        self.spin_rl.setMinimum(0.0)
        self.spin_rl.setMaximum(1.0)
        self.spin_rl.setSingleStep(0.1)
        self.spin_rl.setProperty("value", 0.3)
        self.spin_rl.setObjectName("spin_rl")
        self.spin_d0 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_d0.setGeometry(QtCore.QRect(90, 110, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        self.spin_d0.setFont(font)
        self.spin_d0.setDecimals(1)
        self.spin_d0.setMinimum(1.0)
        self.spin_d0.setMaximum(999999.0)
        self.spin_d0.setSingleStep(0.5)
        self.spin_d0.setProperty("value", 30.0)
        self.spin_d0.setObjectName("spin_d0")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(30, 30, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 41, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(650, 50, 448, 500))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lab_r3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lab_r3.setMinimumSize(QtCore.QSize(220, 220))
        self.lab_r3.setMaximumSize(QtCore.QSize(220, 220))
        self.lab_r3.setText("")
        self.lab_r3.setObjectName("lab_r3")
        self.gridLayout.addWidget(self.lab_r3, 3, 1, 1, 1)
        self.lab_img = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lab_img.setMinimumSize(QtCore.QSize(220, 220))
        self.lab_img.setMaximumSize(QtCore.QSize(220, 220))
        self.lab_img.setText("")
        self.lab_img.setObjectName("lab_img")
        self.gridLayout.addWidget(self.lab_img, 1, 0, 1, 1)
        self.lab_r1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lab_r1.setMinimumSize(QtCore.QSize(220, 220))
        self.lab_r1.setMaximumSize(QtCore.QSize(220, 220))
        self.lab_r1.setText("")
        self.lab_r1.setObjectName("lab_r1")
        self.gridLayout.addWidget(self.lab_r1, 1, 1, 1, 1)
        self.lab_r2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lab_r2.setMinimumSize(QtCore.QSize(220, 220))
        self.lab_r2.setMaximumSize(QtCore.QSize(220, 220))
        self.lab_r2.setText("")
        self.lab_r2.setObjectName("lab_r2")
        self.gridLayout.addWidget(self.lab_r2, 3, 0, 1, 1)
        self.lab_t1 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.lab_t1.setFont(font)
        self.lab_t1.setText("")
        self.lab_t1.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_t1.setObjectName("lab_t1")
        self.gridLayout.addWidget(self.lab_t1, 0, 1, 1, 1)
        self.lab_t2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.lab_t2.setFont(font)
        self.lab_t2.setText("")
        self.lab_t2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_t2.setObjectName("lab_t2")
        self.gridLayout.addWidget(self.lab_t2, 2, 0, 1, 1)
        self.lab_t3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.lab_t3.setFont(font)
        self.lab_t3.setText("")
        self.lab_t3.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_t3.setObjectName("lab_t3")
        self.gridLayout.addWidget(self.lab_t3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 120, 101, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.btn_fft = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_fft.setGeometry(QtCore.QRect(10, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_fft.setFont(font)
        self.btn_fft.setObjectName("btn_fft")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HW4"))
        self.btnFile.setText(_translate("MainWindow", "Load"))
        self.groupBox.setTitle(_translate("MainWindow", "Blur image"))
        self.btn_blur.setText(_translate("MainWindow", "OK"))
        self.rbtn_noise.setText(_translate("MainWindow", "Noise"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Part2"))
        self.label.setText(_translate("MainWindow", "Cut off frequency"))
        self.rbtn_ideal.setText(_translate("MainWindow", "Ideal Filter"))
        self.rbtn_gaussion.setText(_translate("MainWindow", "Gaussion Filter"))
        self.rbtn_butter.setText(_translate("MainWindow", "Butter Filter"))
        self.label_5.setText(_translate("MainWindow", "Cut off frequency"))
        self.label_6.setText(_translate("MainWindow", "Cut off frequency"))
        self.label_8.setText(_translate("MainWindow", "Order"))
        self.rbtn_high.setText(_translate("MainWindow", "High pass"))
        self.rbtn_low.setText(_translate("MainWindow", "Low pass"))
        self.btn_part2.setText(_translate("MainWindow", "OK"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Homo Filter"))
        self.btn_homo.setText(_translate("MainWindow", "OK"))
        self.label_12.setText(_translate("MainWindow", "Cut off"))
        self.label_9.setText(_translate("MainWindow", "Gamma H"))
        self.label_7.setText(_translate("MainWindow", "Gamma L"))
        self.label_2.setText(_translate("MainWindow", "               Original image"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Part1"))
        self.btn_fft.setText(_translate("MainWindow", "FFT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



